'use strict';

function isCompilableModelSpec(spec) {
  return (
    spec &&
    typeof spec === 'object' &&
    spec.type !== 'failed' &&
    spec.type !== 'needs_review' &&
    typeof spec.collection === 'string' &&
    spec.collection.trim() &&
    spec.fields &&
    typeof spec.fields === 'object'
  );
}

/**
 * Generate models.js source for MongoDB (getDB, getCollection).
 */
function generateModelsModuleSource(modelMeta, options) {
  const compiledDbPath = (options && options.dbModulePath) || 'src/db';

  const header = `'use strict';

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT BY HAND.
// Generated by mask-compile for model metadata (MongoDB).

const _path = require('path');
const _fs = require('fs');

let _dbModuleCache;
function _resolveDbModule() {
  if (_dbModuleCache) return _dbModuleCache;
  let dbModulePath = ${JSON.stringify(compiledDbPath)};
  try {
    const raw = _fs.readFileSync(_path.resolve(__dirname, '../compile-config.json'), 'utf8');
    const cfg = JSON.parse(raw);
    if (cfg.dbModulePath && typeof cfg.dbModulePath === 'string') {
      dbModulePath = cfg.dbModulePath;
    }
  } catch (_) { /* use compiled fallback */ }
  const rel = dbModulePath.replace(/\\\\/g, '/').replace(/\\.js$/i, '');
  const resolved = rel.startsWith('..') ? _path.resolve(__dirname, rel) : _path.resolve(__dirname, '../..', rel);
  try {
    _dbModuleCache = require(resolved);
    return _dbModuleCache;
  } catch (err) {
    if (err.code === 'MODULE_NOT_FOUND') {
      throw new Error(
        '[Mask] Cannot find DB module at "' + dbModulePath + '". ' +
        'If you changed "dbModulePath", re-run node mask.compile.cjs (mask.compile.cjs overrideConfig).'
      );
    }
    throw err;
  }
}

const { getDB } = _resolveDbModule();

module.exports = {
`;

  const entries = Object.entries(modelMeta).filter(([, spec]) => isCompilableModelSpec(spec));
  const bodyChunks = entries.map(([hash, spec]) => {
    const { collection, fields, relations } = spec;
    const fieldsLiteral = JSON.stringify(fields, null, 2);
    const relationsLiteral = JSON.stringify(relations || [], null, 2);
    return `  "${hash}": {
    collection: ${JSON.stringify(collection)},
    fields: ${fieldsLiteral},
    relations: ${relationsLiteral},
    async getCollection() {
      const db = await getDB();
      return db.collection(${JSON.stringify(collection)});
    }
  }`;
  });

  const footer = `
};
`;

  return header + bodyChunks.join(',\n\n') + footer;
}

module.exports = { generateModelsModuleSource };
