'use strict';

const { normalizeFilter } = require('./parse-query');
const { getEmbeddedRuntimeSource } = require('./normalize-aggregation-pipeline');

/**
 * Generate queries.js source for MongoDB only.
 */
function generateQueriesModuleSource(queryMeta, profile, options) {
  const db = 'mongodb';
  const compiledDbPath = (options && options.dbModulePath) || 'src/db';
  const embeddedAggNormalizer = getEmbeddedRuntimeSource();

  const header = `'use strict';

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT BY HAND.
// Generated by mask-compile (database: ${db})

const _path = require('path');
const _fs = require('fs');

let _dbModuleCache;
function _resolveDbModule() {
  if (_dbModuleCache) return _dbModuleCache;
  let dbModulePath = ${JSON.stringify(compiledDbPath)};
  try {
    const raw = _fs.readFileSync(_path.resolve(__dirname, '../compile-config.json'), 'utf8');
    const cfg = JSON.parse(raw);
    if (cfg.dbModulePath && typeof cfg.dbModulePath === 'string') {
      dbModulePath = cfg.dbModulePath;
    }
  } catch (_) { /* use compiled fallback */ }
  const rel = dbModulePath.replace(/\\\\/g, '/').replace(/\\.js$/i, '');
  const resolved = rel.startsWith('..') ? _path.resolve(__dirname, rel) : _path.resolve(__dirname, '../..', rel);
  try {
    _dbModuleCache = require(resolved);
    return _dbModuleCache;
  } catch (err) {
    if (err.code === 'MODULE_NOT_FOUND') {
      throw new Error(
        '[Mask] Cannot find DB module at "' + dbModulePath + '". ' +
        'If you changed "dbModulePath", re-run node mask.compile.cjs (mask.compile.cjs overrideConfig).'
      );
    }
    throw err;
  }
}

const { getDB } = _resolveDbModule();

function applyParams(template, params) {
  if (!template || typeof template !== 'object') {
    return template;
  }
  if (Array.isArray(template)) {
    return template.map((value) => applyParams(value, params));
  }
  const result = {};
  const entries = Object.entries(template);
  for (const [key, value] of entries) {
    if (typeof value === 'string' && value.startsWith(':')) {
      const paramName = value.slice(1);
      if (Object.prototype.hasOwnProperty.call(params, paramName)) {
        result[key] = params[paramName];
      } else {
        result[key] = value;
      }
    } else {
      result[key] = applyParams(value, params);
    }
  }
  return result;
}

/** Like applyParams for insert documents: drop keys whose value is :param when param is not passed (optional fields). */
function applyParamsDocument(template, params) {
  if (!template || typeof template !== 'object') {
    return template;
  }
  if (Array.isArray(template)) {
    return template.map((v) => applyParamsDocument(v, params));
  }
  const result = {};
  const p = params && typeof params === 'object' ? params : {};
  for (const [key, value] of Object.entries(template)) {
    if (typeof value === 'string' && value.startsWith(':')) {
      const paramName = value.slice(1);
      if (Object.prototype.hasOwnProperty.call(p, paramName)) {
        result[key] = p[paramName];
      }
      continue;
    }
    if (value !== null && typeof value === 'object') {
      const nested = applyParamsDocument(value, p);
      if (Array.isArray(nested)) {
        result[key] = nested;
      } else if (nested && typeof nested === 'object') {
        if (Object.keys(nested).length > 0) {
          result[key] = nested;
        }
      } else {
        result[key] = nested;
      }
      continue;
    }
    result[key] = value;
  }
  return result;
}

function getParamNamesFromTemplate(template) {
  const names = new Set();
  function walk(obj) {
    if (obj === null || typeof obj !== 'object') return;
    if (Array.isArray(obj)) { obj.forEach(walk); return; }
    for (const v of Object.values(obj)) {
      if (typeof v === 'string' && v.startsWith(':')) names.add(v.slice(1));
      else walk(v);
    }
  }
  walk(template);
  return names;
}

function normalizeMongoDriverOptions(specOpts) {
  const merged = Object.assign({}, specOpts || {});
  if (merged.returnDocument === true) {
    merged.returnDocument = 'after';
  }
  return merged;
}

function mongoWantsReturnedDocument(merged) {
  if (!merged || typeof merged !== 'object') return false;
  if (merged.returnDocument === true) return true;
  if (merged.returnDocument === 'after' || merged.returnDocument === 'before') return true;
  return false;
}

function omitMongoReturnDocumentKeys(opts) {
  if (!opts || typeof opts !== 'object') return {};
  const copy = { ...opts };
  delete copy.returnDocument;
  return copy;
}

/** Resolve find skip/limit from compiled spec: number, numeric string, or :paramName → params[param]. */
function resolvePagingNumber(specValue, params) {
  if (specValue === undefined || specValue === null) return undefined;
  if (typeof specValue === 'number' && Number.isFinite(specValue)) return Math.trunc(specValue);
  if (typeof specValue === 'string') {
    if (/^-?\\d+$/.test(specValue)) return parseInt(specValue, 10);
    const m = specValue.match(/^:(\\w+)$/);
    if (m) {
      const v = params[m[1]];
      if (typeof v === 'number' && Number.isFinite(v)) return Math.trunc(v);
      if (typeof v === 'string' && /^-?\\d+$/.test(v)) return parseInt(v, 10);
    }
  }
  return undefined;
}

function ensureMongoUpdateDocument(update) {
  if (!update || typeof update !== 'object' || Array.isArray(update)) {
    throw new Error('[Mask] Invalid compiled update document. Re-run node mask.compile.cjs.');
  }
  const keys = Object.keys(update);
  if (keys.length === 0) {
    throw new Error(
      '[Mask] Update is empty (compiled updateTemplate had no fields). Re-run node mask.compile.cjs or rephrase the prompt so the model emits field updates.'
    );
  }
  if (keys.some((k) => k.startsWith('$'))) {
    return update;
  }
  return { $set: update };
}

${embeddedAggNormalizer}

module.exports = {
`;

  const entries = Object.entries(queryMeta);
  const bodyChunks = entries.map(([hash, spec]) => {
    if (spec.type === 'failed') {
      return `  "${hash}": async function () {
    return undefined;
  }`;
    }
    if (spec.type === 'needs_review') {
      const raw = spec.warning || 'Prompt is unclear or nonsensical.';
      const warning = String(raw).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$').replace(/\n/g, ' ');
      return `  "${hash}": async function () {
    throw new Error(\`[Mask] This prompt needs review. Fix it and re-run compile. Reason: ${warning}\`);
  }`;
    }
    if (spec.type === 'aggregation') {
      const { collection, pipeline } = spec;
      const pipelineLiteral = JSON.stringify(pipeline || [], null, 2);
      const driverOptsLiteral = JSON.stringify(spec.driverOptions || {});
      return `  "${hash}": async function (params = {}, options = {}) {
    const db = await getDB();
    const coll = db.collection(${JSON.stringify(collection)});
    const pipelineTemplate = ${pipelineLiteral};
    const pipeline = normalizeAggregationPipeline(applyParams(pipelineTemplate, params));
    const merged = normalizeMongoDriverOptions(${driverOptsLiteral});
    return coll.aggregate(pipeline, omitMongoReturnDocumentKeys(merged)).toArray();
  }`;
    }
    if (spec.type === 'insert') {
      const { collection, documentTemplate, documentFromParams } = spec;
      const driverOptsLiteral = JSON.stringify(spec.driverOptions || {});
      if (documentFromParams) {
        return `  "${hash}": async function (params = {}, options = {}) {
    const db = await getDB();
    const coll = db.collection(${JSON.stringify(collection)});
    const merged = normalizeMongoDriverOptions(${driverOptsLiteral});
    const insertOpts = omitMongoReturnDocumentKeys(merged);
    const result = await coll.insertOne(params, insertOpts);
    if (mongoWantsReturnedDocument(merged)) {
      return coll.findOne({ _id: result.insertedId });
    }
    return result;
  }`;
      }
      const docLiteral = JSON.stringify(documentTemplate || {}, null, 2);
      return `  "${hash}": async function (params = {}, options = {}) {
    const db = await getDB();
    const coll = db.collection(${JSON.stringify(collection)});
    const merged = normalizeMongoDriverOptions(${driverOptsLiteral});
    const insertOpts = omitMongoReturnDocumentKeys(merged);
    const document = applyParamsDocument(${docLiteral}, params);
    const result = await coll.insertOne(document, insertOpts);
    if (mongoWantsReturnedDocument(merged)) {
      return coll.findOne({ _id: result.insertedId });
    }
    return result;
  }`;
    }
    if (spec.type === 'update') {
      const { collection, filter, updateTemplate, setFieldsFromParams, oneOrMany } = spec;
      const filterLiteral = JSON.stringify(filter || {}, null, 2);
      const method = oneOrMany === 'many' ? 'updateMany' : 'updateOne';
      const driverOptsLiteral = JSON.stringify(spec.driverOptions || {});
      const oneOrManyLit = JSON.stringify(oneOrMany === 'many' ? 'many' : 'one');
      if (setFieldsFromParams) {
        return `  "${hash}": async function (params = {}, options = {}) {
    const db = await getDB();
    const coll = db.collection(${JSON.stringify(collection)});
    const merged = normalizeMongoDriverOptions(${driverOptsLiteral});
    const filterTemplate = ${filterLiteral};
    const filterParamNames = getParamNamesFromTemplate(filterTemplate);
    const filter = applyParams(filterTemplate, params);
    const updateFields = {};
    for (const [k, v] of Object.entries(params)) {
      if (!filterParamNames.has(k)) updateFields[k] = v;
    }
    if (${oneOrManyLit} === 'one' && mongoWantsReturnedDocument(merged)) {
      return coll.findOneAndUpdate(filter, { $set: updateFields }, merged);
    }
    const result = await coll.${method}(filter, { $set: updateFields }, omitMongoReturnDocumentKeys(merged));
    return result;
  }`;
      }
      const updateLiteral = JSON.stringify(updateTemplate || {}, null, 2);
      return `  "${hash}": async function (params = {}, options = {}) {
    const db = await getDB();
    const coll = db.collection(${JSON.stringify(collection)});
    const merged = normalizeMongoDriverOptions(${driverOptsLiteral});
    const filterTemplate = ${filterLiteral};
    const filter = applyParams(filterTemplate, params);
    const updateTemplateObj = ${updateLiteral};
    const update = ensureMongoUpdateDocument(applyParams(updateTemplateObj, params));
    if (${oneOrManyLit} === 'one' && mongoWantsReturnedDocument(merged)) {
      return coll.findOneAndUpdate(filter, update, merged);
    }
    const result = await coll.${method}(filter, update, omitMongoReturnDocumentKeys(merged));
    return result;
  }`;
    }
    if (spec.type === 'delete') {
      const { collection, filter, oneOrMany } = spec;
      const filterLiteral = JSON.stringify(filter || {}, null, 2);
      const method = oneOrMany === 'many' ? 'deleteMany' : 'deleteOne';
      const driverOptsLiteral = JSON.stringify(spec.driverOptions || {});
      const oneOrManyLit = JSON.stringify(oneOrMany === 'many' ? 'many' : 'one');
      return `  "${hash}": async function (params = {}, options = {}) {
    const db = await getDB();
    const coll = db.collection(${JSON.stringify(collection)});
    const merged = normalizeMongoDriverOptions(${driverOptsLiteral});
    const filterTemplate = ${filterLiteral};
    const filter = applyParams(filterTemplate, params);
    if (${oneOrManyLit} === 'one' && mongoWantsReturnedDocument(merged)) {
      return coll.findOneAndDelete(filter, merged);
    }
    const result = await coll.${method}(filter, omitMongoReturnDocumentKeys(merged));
    return result;
  }`;
    }

    const { collection, filter, projection, sort, limit, skip } = spec;
    const normalizedFilter = normalizeFilter(filter || {});
    const filterLiteral = JSON.stringify(normalizedFilter, null, 2);
    const projectionLiteral = projection ? JSON.stringify(projection, null, 2) : 'undefined';
    const sortLiteral = sort ? JSON.stringify(sort, null, 2) : 'undefined';
    const skipSpecLiteral = skip !== undefined && skip !== null ? JSON.stringify(skip) : 'undefined';
    const limitSpecLiteral = limit !== undefined && limit !== null ? JSON.stringify(limit) : 'undefined';
    const driverOptsLiteral = JSON.stringify(spec.driverOptions || {});

    return `  "${hash}": async function (params = {}, options = {}) {
    const db = await getDB();
    const collection = db.collection(${JSON.stringify(collection)});
    const merged = normalizeMongoDriverOptions(${driverOptsLiteral});
    const filterTemplate = ${filterLiteral};
    const projectionTemplate = ${projectionLiteral};
    const sortTemplate = ${sortLiteral};
    const skipSpec = ${skipSpecLiteral};
    const limitSpec = ${limitSpecLiteral};
    const filter = applyParams(filterTemplate, params);
    const findOpts = {};
    if (projectionTemplate && typeof projectionTemplate === 'object') {
      findOpts.projection = applyParams(projectionTemplate, params);
    }
    Object.assign(findOpts, omitMongoReturnDocumentKeys(merged));
    let cursor = collection.find(filter, findOpts);
    if (sortTemplate && typeof sortTemplate === 'object') {
      const sortSpec = applyParams(sortTemplate, params);
      cursor = cursor.sort(sortSpec);
    }
    const skipN = resolvePagingNumber(skipSpec, params);
    const limitN = resolvePagingNumber(limitSpec, params);
    if (typeof skipN === 'number') {
      cursor = cursor.skip(skipN);
    }
    if (typeof limitN === 'number') {
      cursor = cursor.limit(limitN);
    }
    return cursor.toArray();
  }`;
  });

  const footer = `
};
`;

  return header + bodyChunks.join(',\n\n') + footer;
}

module.exports = { generateQueriesModuleSource };
