'use strict';

/**
 * Generate queries.js source for SQL only (MySQL/PostgreSQL).
 */
function generateQueriesModuleSource(queryMeta, profile, options) {
  const db = (profile && profile.database) ? String(profile.database).toLowerCase() : 'mysql';
  const compiledDbPath = (options && options.dbModulePath) || 'src/db';

  const header = `'use strict';

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT BY HAND.
// Generated by mask-compile (database: ${db})

const _path = require('path');
const _fs = require('fs');

let _dbModuleCache;
function _resolveDbModule() {
  if (_dbModuleCache) return _dbModuleCache;
  let dbModulePath = ${JSON.stringify(compiledDbPath)};
  try {
    const raw = _fs.readFileSync(_path.resolve(__dirname, '../compile-config.json'), 'utf8');
    const cfg = JSON.parse(raw);
    if (cfg.dbModulePath && typeof cfg.dbModulePath === 'string') {
      dbModulePath = cfg.dbModulePath;
    }
  } catch (_) { /* use compiled fallback */ }
  const rel = dbModulePath.replace(/\\\\/g, '/').replace(/\\.js$/i, '');
  const resolved = rel.startsWith('..') ? _path.resolve(__dirname, rel) : _path.resolve(__dirname, '../..', rel);
  try {
    _dbModuleCache = require(resolved);
    return _dbModuleCache;
  } catch (err) {
    if (err.code === 'MODULE_NOT_FOUND') {
      throw new Error(
        '[Mask] Cannot find DB module at "' + dbModulePath + '". ' +
        'If you changed "dbModulePath", re-run node mask.compile.cjs (mask.compile.cjs overrideConfig).'
      );
    }
    throw err;
  }
}

const { getSqlConnection } = _resolveDbModule();

function applyParams(template, params) {
  if (!template || typeof template !== 'object') {
    return template;
  }
  if (Array.isArray(template)) {
    return template.map((value) => applyParams(value, params));
  }
  const result = {};
  const entries = Object.entries(template);
  for (const [key, value] of entries) {
    if (typeof value === 'string' && value.startsWith(':')) {
      const paramName = value.slice(1);
      if (Object.prototype.hasOwnProperty.call(params, paramName)) {
        result[key] = params[paramName];
      } else {
        result[key] = value;
      }
    } else {
      result[key] = applyParams(value, params);
    }
  }
  return result;
}

function getParamNamesFromTemplate(template) {
  const names = new Set();
  function walk(obj) {
    if (obj === null || typeof obj !== 'object') return;
    if (Array.isArray(obj)) { obj.forEach(walk); return; }
    for (const v of Object.values(obj)) {
      if (typeof v === 'string' && v.startsWith(':')) names.add(v.slice(1));
      else walk(v);
    }
  }
  walk(template);
  return names;
}

/** Left-to-right :param → ? or $n; one binding per occurrence (duplicate :id → duplicate values). */
function buildSqlBinding(queryTemplate, params, dialect) {
  const d = dialect != null && dialect !== '' ? String(dialect).toLowerCase() : 'mysql';
  const useNumbered = d === 'postgres' || d === 'postgresql';
  const values = [];
  let n = 0;
  const sql = queryTemplate.replace(/:(\\w+)/g, (_, name) => {
    if (!Object.prototype.hasOwnProperty.call(params, name)) {
      throw new Error('[Mask] SQL missing param value for :' + name);
    }
    values.push(params[name]);
    if (useNumbered) {
      n += 1;
      return '$' + n;
    }
    return '?';
  });
  return { sql, values };
}

module.exports = {
`;

  const entries = Object.entries(queryMeta);
  const bodyChunks = entries.map(([hash, spec]) => {
    if (spec.type === 'failed') {
      return `  "${hash}": async function () {
    return undefined;
  }`;
    }
    if (spec.type === 'needs_review') {
      const raw = spec.warning || 'Prompt is unclear or nonsensical.';
      const warning = String(raw).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$').replace(/\n/g, ' ');
      return `  "${hash}": async function () {
    throw new Error(\`[Mask] This prompt needs review. Fix it and re-run compile. Reason: ${warning}\`);
  }`;
    }
    if (spec.query && ['select', 'insert', 'update', 'delete'].includes(spec.type)) {
      const dialectLiteral = JSON.stringify(
        spec.dialect != null && spec.dialect !== '' ? String(spec.dialect).toLowerCase() : ''
      );
      const queryEscaped = JSON.stringify(spec.query);
      return `  "${hash}": async function (params = {}, options = {}) {
    const conn = await getSqlConnection();
    const dialect = ${dialectLiteral} || (${JSON.stringify(db)} === 'postgres' || ${JSON.stringify(db)} === 'postgresql' ? 'postgres' : 'mysql');
    const { sql, values } = buildSqlBinding(${queryEscaped}, params, dialect);
    const [rows] = await conn.execute(sql, values);
    return rows;
  }`;
    }

    return `  "${hash}": async function () {
    return undefined;
  }`;
  });

  const footer = `
};
`;

  return header + bodyChunks.join(',\n\n') + footer;
}

module.exports = { generateQueriesModuleSource };
