'use strict';

function isCompilableModelSpec(spec) {
  return (
    spec &&
    typeof spec === 'object' &&
    spec.type !== 'failed' &&
    spec.type !== 'needs_review' &&
    typeof spec.collection === 'string' &&
    spec.collection.trim() &&
    spec.fields &&
    typeof spec.fields === 'object'
  );
}

function generateModelsModuleSource(modelMeta, options) {
  const header = `'use strict';

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT BY HAND.
// Generated by mask-compile for model metadata (Neo4j).

module.exports = {
`;

  const entries = Object.entries(modelMeta).filter(([, spec]) => isCompilableModelSpec(spec));
  const bodyChunks = entries.map(([hash, spec]) => {
    const { collection, fields, relations } = spec;
    const fieldsLiteral = JSON.stringify(fields, null, 2);
    const relationsLiteral = JSON.stringify(relations || [], null, 2);
    return `  "${hash}": {
    collection: ${JSON.stringify(collection)},
    fields: ${fieldsLiteral},
    relations: ${relationsLiteral}
  }`;
  });

  const footer = `
};
`;
  return header + bodyChunks.join(',\n\n') + footer;
}

module.exports = { generateModelsModuleSource };
