'use strict';

function generateQueriesModuleSource(queryMeta, profile, options) {
  const db = 'neo4j';
  const compiledDbPath = (options && options.dbModulePath) || 'src/db';

  const header = `'use strict';

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT BY HAND.
// Generated by mask-compile (database: ${db})

const _path = require('path');
const _fs = require('fs');

let _dbModuleCache;
function _resolveDbModule() {
  if (_dbModuleCache) return _dbModuleCache;
  let dbModulePath = ${JSON.stringify(compiledDbPath)};
  try {
    const raw = _fs.readFileSync(_path.resolve(__dirname, '../compile-config.json'), 'utf8');
    const cfg = JSON.parse(raw);
    if (cfg.dbModulePath && typeof cfg.dbModulePath === 'string') {
      dbModulePath = cfg.dbModulePath;
    }
  } catch (_) { /* use compiled fallback */ }
  const rel = dbModulePath.replace(/\\\\/g, '/').replace(/\\.js$/i, '');
  const resolved = rel.startsWith('..') ? _path.resolve(__dirname, rel) : _path.resolve(__dirname, '../..', rel);
  try {
    _dbModuleCache = require(resolved);
    return _dbModuleCache;
  } catch (err) {
    if (err.code === 'MODULE_NOT_FOUND') {
      throw new Error(
        '[Mask] Cannot find DB module at "' + dbModulePath + '". ' +
        'If you changed "dbModulePath", re-run node mask.compile.cjs (mask.compile.cjs overrideConfig).'
      );
    }
    throw err;
  }
}

const { getNeo4jSession } = _resolveDbModule();

module.exports = {
`;

  const entries = Object.entries(queryMeta);
  const bodyChunks = entries.map(([hash, spec]) => {
    if (spec.type === 'failed') {
      return `  "${hash}": async function () { return undefined; }`;
    }
    if (spec.type === 'needs_review') {
      const raw = spec.warning || 'Prompt is unclear or nonsensical.';
      const warning = String(raw).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$').replace(/\n/g, ' ');
      return `  "${hash}": async function () {
    throw new Error(\`[Mask] This prompt needs review. Fix it and re-run compile. Reason: ${warning}\`);
  }`;
    }
    if (spec.cypher && ['read', 'write'].includes(spec.type)) {
      const paramList = Array.isArray(spec.params) ? spec.params : [];
      const cypherEscaped = JSON.stringify(spec.cypher);
      const isRead = spec.type === 'read';
      const paramAssigns = paramList.length
        ? paramList.map((p) => `paramObj[${JSON.stringify(p)}] = params[${JSON.stringify(p)}];`).join('\n    ')
        : '';
      const returnExpr = isRead
        ? 'result.records.map((r) => r.toObject())'
        : '{ records: result.records.map((r) => r.toObject()), counters: result.summary.counters.updates() }';
      const sessionModeLit = JSON.stringify(
        spec.sessionMode && ['read', 'write', 'run'].includes(String(spec.sessionMode).toLowerCase())
          ? String(spec.sessionMode).toLowerCase()
          : 'run'
      );
      return `  "${hash}": async function (params = {}, options = {}) {
    const session = await getNeo4jSession();
    const sessionMode = ${sessionModeLit};
    try {
      const paramObj = {};
      ${paramAssigns}
      const cypher = ${cypherEscaped};
      if (sessionMode === 'read') {
        const out = await session.executeRead((tx) => tx.run(cypher, paramObj));
        return ${returnExpr.replace(/result\./g, 'out.')};
      }
      if (sessionMode === 'write') {
        const out = await session.executeWrite((tx) => tx.run(cypher, paramObj));
        return ${returnExpr.replace(/result\./g, 'out.')};
      }
      const result = await session.run(cypher, paramObj);
      return ${returnExpr};
    } finally {
      await session.close();
    }
  }`;
    }
    return `  "${hash}": async function () { return undefined; }`;
  });

  const footer = `
};
`;
  return header + bodyChunks.join(',\n\n') + footer;
}

module.exports = { generateQueriesModuleSource };
