'use strict';

const { normalizeFilter } = require('../../mongo-db/compiler/parse-query');
const { getEmbeddedRuntimeSource } = require('../../mongo-db/compiler/normalize-aggregation-pipeline');

function findModelHashForCollection(modelMeta, collection) {
  const want = String(collection || '').toLowerCase();
  for (const [h, spec] of Object.entries(modelMeta || {})) {
    if (spec && String(spec.collection || '').toLowerCase() === want) {
      return h;
    }
  }
  return null;
}

/**
 * Generate queries.js for Mongoose (compiled operations use Models + validation).
 */
function generateQueriesModuleSource(queryMeta, profile, options) {
  const db = 'mongoose';
  const modelMeta = (options && options.modelMeta) || {};
  const modelsRequire = `const compiledModels = require('./models');`;
  const embeddedAggNormalizer = getEmbeddedRuntimeSource();

  const header = `'use strict';

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT BY HAND.
// Generated by mask-compile (database: ${db})

${modelsRequire}

function applyParams(template, params) {
  if (!template || typeof template !== 'object') {
    return template;
  }
  if (Array.isArray(template)) {
    return template.map((value) => applyParams(value, params));
  }
  const result = {};
  const entries = Object.entries(template);
  for (const [key, value] of entries) {
    if (typeof value === 'string' && value.startsWith(':')) {
      const paramName = value.slice(1);
      if (Object.prototype.hasOwnProperty.call(params, paramName)) {
        result[key] = params[paramName];
      } else {
        result[key] = value;
      }
    } else {
      result[key] = applyParams(value, params);
    }
  }
  return result;
}

function applyParamsDocument(template, params) {
  if (!template || typeof template !== 'object') {
    return template;
  }
  if (Array.isArray(template)) {
    return template.map((v) => applyParamsDocument(v, params));
  }
  const result = {};
  const p = params && typeof params === 'object' ? params : {};
  for (const [key, value] of Object.entries(template)) {
    if (typeof value === 'string' && value.startsWith(':')) {
      const paramName = value.slice(1);
      if (Object.prototype.hasOwnProperty.call(p, paramName)) {
        result[key] = p[paramName];
      }
      continue;
    }
    if (value !== null && typeof value === 'object') {
      const nested = applyParamsDocument(value, p);
      if (Array.isArray(nested)) {
        result[key] = nested;
      } else if (nested && typeof nested === 'object') {
        if (Object.keys(nested).length > 0) {
          result[key] = nested;
        }
      } else {
        result[key] = nested;
      }
      continue;
    }
    result[key] = value;
  }
  return result;
}

function getParamNamesFromTemplate(template) {
  const names = new Set();
  function walk(obj) {
    if (obj === null || typeof obj !== 'object') return;
    if (Array.isArray(obj)) {
      obj.forEach(walk);
      return;
    }
    for (const v of Object.values(obj)) {
      if (typeof v === 'string' && v.startsWith(':')) names.add(v.slice(1));
      else walk(v);
    }
  }
  walk(template);
  return names;
}

function normalizeMongooseDriverOptions(specOpts) {
  const merged = Object.assign({}, specOpts || {});
  if (merged.returnDocument === true) {
    merged.new = true;
    delete merged.returnDocument;
  } else if (merged.returnDocument === 'after') {
    merged.new = true;
    delete merged.returnDocument;
  } else if (merged.returnDocument === 'before') {
    merged.new = false;
    delete merged.returnDocument;
  }
  return merged;
}

function mongooseWantsReturnedDocument(merged) {
  if (!merged || typeof merged !== 'object') return false;
  if (merged.new === true) return true;
  if (merged.returnOriginal === false) return true;
  return false;
}

function omitMongooseWriteReturnKeys(opts) {
  if (!opts || typeof opts !== 'object') return {};
  const copy = { ...opts };
  delete copy.returnDocument;
  delete copy.new;
  delete copy.returnOriginal;
  return copy;
}

/** Resolve find skip/limit from compiled spec: number, numeric string, or :paramName → params[param]. */
function resolvePagingNumber(specValue, params) {
  if (specValue === undefined || specValue === null) return undefined;
  if (typeof specValue === 'number' && Number.isFinite(specValue)) return Math.trunc(specValue);
  if (typeof specValue === 'string') {
    if (/^-?\\d+$/.test(specValue)) return parseInt(specValue, 10);
    const m = specValue.match(/^:(\\w+)$/);
    if (m) {
      const v = params[m[1]];
      if (typeof v === 'number' && Number.isFinite(v)) return Math.trunc(v);
      if (typeof v === 'string' && /^-?\\d+$/.test(v)) return parseInt(v, 10);
    }
  }
  return undefined;
}

function ensureMongoUpdateDocument(update) {
  if (!update || typeof update !== 'object' || Array.isArray(update)) {
    throw new Error('[Mask] Invalid compiled update document. Re-run node mask.compile.cjs.');
  }
  const keys = Object.keys(update);
  if (keys.length === 0) {
    throw new Error(
      '[Mask] Update is empty (compiled updateTemplate had no fields). Re-run node mask.compile.cjs or rephrase the prompt so the model emits field updates.'
    );
  }
  if (keys.some((k) => k.startsWith('$'))) {
    return update;
  }
  return { $set: update };
}

${embeddedAggNormalizer}

module.exports = {
`;

  const entries = Object.entries(queryMeta);
  const bodyChunks = entries.map(([hash, spec]) => {
    if (spec.type === 'failed') {
      return `  "${hash}": async function () {
    return undefined;
  }`;
    }
    if (spec.type === 'needs_review') {
      const raw = spec.warning || 'Prompt is unclear or nonsensical.';
      const warning = String(raw).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$').replace(/\n/g, ' ');
      return `  "${hash}": async function () {
    throw new Error(\`[Mask] This prompt needs review. Fix it and re-run compile. Reason: ${warning}\`);
  }`;
    }

    const collection = spec.collection;
    const modelHash = findModelHashForCollection(modelMeta, collection);
    if (!modelHash) {
      return `  "${hash}": async function () {
    throw new Error(${JSON.stringify(
        `[Mask] No Mongoose model compiled for collection "${collection}". Add MaskModels.define() for this collection and re-run node mask.compile.cjs.`
      )});
  }`;
    }
    const modelHashLit = JSON.stringify(modelHash);

    if (spec.type === 'aggregation') {
      const pipelineLiteral = JSON.stringify(spec.pipeline || [], null, 2);
      const driverOptsLiteral = JSON.stringify(spec.driverOptions || {});
      return `  "${hash}": async function (params = {}, options = {}) {
    const Model = await compiledModels[${modelHashLit}].getModel();
    const merged = normalizeMongooseDriverOptions(${driverOptsLiteral});
    const pipelineTemplate = ${pipelineLiteral};
    const pipeline = normalizeAggregationPipeline(applyParams(pipelineTemplate, params));
    return Model.aggregate(pipeline, omitMongooseWriteReturnKeys(merged));
  }`;
    }
    if (spec.type === 'insert') {
      const { documentTemplate, documentFromParams } = spec;
      const driverOptsLiteral = JSON.stringify(spec.driverOptions || {});
      if (documentFromParams) {
        return `  "${hash}": async function (params = {}, options = {}) {
    const Model = await compiledModels[${modelHashLit}].getModel();
    const merged = normalizeMongooseDriverOptions(${driverOptsLiteral});
    const doc = new Model(params);
    return doc.save(omitMongooseWriteReturnKeys(merged));
  }`;
      }
      const docLiteral = JSON.stringify(documentTemplate || {}, null, 2);
      return `  "${hash}": async function (params = {}, options = {}) {
    const Model = await compiledModels[${modelHashLit}].getModel();
    const merged = normalizeMongooseDriverOptions(${driverOptsLiteral});
    const document = applyParamsDocument(${docLiteral}, params);
    const doc = new Model(document);
    return doc.save(omitMongooseWriteReturnKeys(merged));
  }`;
    }
    if (spec.type === 'update') {
      const { filter, updateTemplate, setFieldsFromParams, oneOrMany } = spec;
      const filterLiteral = JSON.stringify(filter || {}, null, 2);
      const method = oneOrMany === 'many' ? 'updateMany' : 'updateOne';
      const findOneMethod = 'findOneAndUpdate';
      const driverOptsLiteral = JSON.stringify(spec.driverOptions || {});
      const oneOrManyLit = JSON.stringify(oneOrMany === 'many' ? 'many' : 'one');
      if (setFieldsFromParams) {
        return `  "${hash}": async function (params = {}, options = {}) {
    const Model = await compiledModels[${modelHashLit}].getModel();
    const merged = normalizeMongooseDriverOptions(${driverOptsLiteral});
    const filterTemplate = ${filterLiteral};
    const filterParamNames = getParamNamesFromTemplate(filterTemplate);
    const filterObj = applyParams(filterTemplate, params);
    const updateFields = {};
    for (const [k, v] of Object.entries(params)) {
      if (!filterParamNames.has(k)) updateFields[k] = v;
    }
    if (${oneOrManyLit} === 'one' && mongooseWantsReturnedDocument(merged)) {
      return Model.${findOneMethod}(filterObj, { $set: updateFields }, merged);
    }
    return Model.${method}(filterObj, { $set: updateFields }, omitMongooseWriteReturnKeys(merged));
  }`;
      }
      const updateLiteral = JSON.stringify(updateTemplate || {}, null, 2);
      return `  "${hash}": async function (params = {}, options = {}) {
    const Model = await compiledModels[${modelHashLit}].getModel();
    const merged = normalizeMongooseDriverOptions(${driverOptsLiteral});
    const filterTemplate = ${filterLiteral};
    const filterObj = applyParams(filterTemplate, params);
    const updateTemplateObj = ${updateLiteral};
    const update = ensureMongoUpdateDocument(applyParams(updateTemplateObj, params));
    if (${oneOrManyLit} === 'one' && mongooseWantsReturnedDocument(merged)) {
      return Model.${findOneMethod}(filterObj, update, merged);
    }
    return Model.${method}(filterObj, update, omitMongooseWriteReturnKeys(merged));
  }`;
    }
    if (spec.type === 'delete') {
      const { filter, oneOrMany } = spec;
      const filterLiteral = JSON.stringify(filter || {}, null, 2);
      const method = oneOrMany === 'many' ? 'deleteMany' : 'deleteOne';
      const driverOptsLiteral = JSON.stringify(spec.driverOptions || {});
      const oneOrManyLit = JSON.stringify(oneOrMany === 'many' ? 'many' : 'one');
      return `  "${hash}": async function (params = {}, options = {}) {
    const Model = await compiledModels[${modelHashLit}].getModel();
    const merged = normalizeMongooseDriverOptions(${driverOptsLiteral});
    const filterTemplate = ${filterLiteral};
    const filterObj = applyParams(filterTemplate, params);
    if (${oneOrManyLit} === 'one' && mongooseWantsReturnedDocument(merged)) {
      return Model.findOneAndDelete(filterObj, merged);
    }
    return Model.${method}(filterObj, omitMongooseWriteReturnKeys(merged));
  }`;
    }

    const { filter, projection, sort, limit, skip } = spec;
    const normalizedFilter = normalizeFilter(filter || {});
    const filterLiteral = JSON.stringify(normalizedFilter, null, 2);
    const projectionLiteral = projection ? JSON.stringify(projection, null, 2) : 'undefined';
    const sortLiteral = sort ? JSON.stringify(sort, null, 2) : 'undefined';
    const skipSpecLiteral = skip !== undefined && skip !== null ? JSON.stringify(skip) : 'undefined';
    const limitSpecLiteral = limit !== undefined && limit !== null ? JSON.stringify(limit) : 'undefined';
    const driverOptsLiteral = JSON.stringify(spec.driverOptions || {});

    return `  "${hash}": async function (params = {}, options = {}) {
    const Model = await compiledModels[${modelHashLit}].getModel();
    const merged = normalizeMongooseDriverOptions(${driverOptsLiteral});
    const filterTemplate = ${filterLiteral};
    const projectionTemplate = ${projectionLiteral};
    const sortTemplate = ${sortLiteral};
    const skipSpec = ${skipSpecLiteral};
    const limitSpec = ${limitSpecLiteral};
    const filterObj = applyParams(filterTemplate, params);
    const findOpts = omitMongooseWriteReturnKeys(merged);
    let q = Object.keys(findOpts).length ? Model.find(filterObj, null, findOpts) : Model.find(filterObj);
    if (projectionTemplate && typeof projectionTemplate === 'object') {
      const proj = applyParams(projectionTemplate, params);
      q = q.select(proj);
    }
    if (sortTemplate && typeof sortTemplate === 'object') {
      const sortSpec = applyParams(sortTemplate, params);
      q = q.sort(sortSpec);
    }
    const skipN = resolvePagingNumber(skipSpec, params);
    const limitN = resolvePagingNumber(limitSpec, params);
    if (typeof skipN === 'number') {
      q = q.skip(skipN);
    }
    if (typeof limitN === 'number') {
      q = q.limit(limitN);
    }
    return q.lean();
  }`;
  });

  const footer = `
};
`;

  void profile;
  return header + bodyChunks.join(',\n\n') + footer;
}

module.exports = { generateQueriesModuleSource };
