'use strict';

const { buildPathsObjectSource, inferModelName } = require('./mongoose-paths');

function isCompilableModelSpec(spec) {
  return (
    spec &&
    typeof spec === 'object' &&
    spec.type !== 'failed' &&
    spec.type !== 'needs_review' &&
    typeof spec.collection === 'string' &&
    spec.collection.trim() &&
    spec.fields &&
    typeof spec.fields === 'object'
  );
}

/**
 * Generate models.js: real mongoose.Schema factories + getModel() for query codegen.
 */
function generateModelsModuleSource(modelMeta, options) {
  const compiledDbPath = (options && options.dbModulePath) || 'src/db';

  const entries = Object.entries(modelMeta || {}).filter(([, spec]) => isCompilableModelSpec(spec));
  const bodyChunks = entries.map(([hash, spec]) => {
    const collection = spec && spec.collection ? String(spec.collection) : '';
    const modelName = inferModelName(spec);
    const pathsSource = buildPathsObjectSource(spec && spec.fields ? spec.fields : {});
    const fieldsLiteral = JSON.stringify(spec.fields || {}, null, 2);
    const relationsLiteral = JSON.stringify(spec.relations || [], null, 2);
    const schemaOptionsLiteral = JSON.stringify(spec.schemaOptions || {});

    return `  ${JSON.stringify(hash)}: (function () {
    let _schema;
    const modelName = ${JSON.stringify(modelName)};
    const collection = ${JSON.stringify(collection)};
    const fields = ${fieldsLiteral};
    const relations = ${relationsLiteral};
    function buildSchema() {
      const mongoose = require('mongoose');
      if (!_schema) {
        const schemaOpts = Object.assign({}, ${schemaOptionsLiteral}, { collection });
        _schema = new mongoose.Schema(
    ${pathsSource},
          schemaOpts
        );
      }
      return _schema;
    }
    async function getModel() {
      const { getMongooseConnection } = _resolveDbModule();
      const conn = await getMongooseConnection();
      if (conn.models[modelName]) {
        return conn.models[modelName];
      }
      return conn.model(modelName, buildSchema());
    }
    return {
      modelName,
      collection,
      fields,
      relations,
      buildSchema,
      getModel
    };
  })()`;
  });

  const header = `'use strict';

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT BY HAND.
// Generated by mask-compile for Mongoose (schemas + models).

const _path = require('path');
const _fs = require('fs');

let _dbModuleCache;
function _resolveDbModule() {
  if (_dbModuleCache) return _dbModuleCache;
  let dbModulePath = ${JSON.stringify(compiledDbPath)};
  try {
    const raw = _fs.readFileSync(_path.resolve(__dirname, '../compile-config.json'), 'utf8');
    const cfg = JSON.parse(raw);
    if (cfg.dbModulePath && typeof cfg.dbModulePath === 'string') {
      dbModulePath = cfg.dbModulePath;
    }
  } catch (_) { /* use compiled fallback */ }
  const rel = dbModulePath.replace(/\\\\/g, '/').replace(/\\.js$/i, '');
  const resolved = rel.startsWith('..') ? _path.resolve(__dirname, rel) : _path.resolve(__dirname, '../..', rel);
  try {
    _dbModuleCache = require(resolved);
    return _dbModuleCache;
  } catch (err) {
    if (err.code === 'MODULE_NOT_FOUND') {
      throw new Error(
        '[Mask] Cannot find DB module at "' + dbModulePath + '". ' +
        'If you changed "dbModulePath", re-run node mask.compile.cjs (mask.compile.cjs overrideConfig).'
      );
    }
    throw err;
  }
}

module.exports = {
`;

  const footer = `
};
`;

  return header + bodyChunks.join(',\n\n') + footer;
}

module.exports = { generateModelsModuleSource };
